- styles/index.css
1. Default font-size went from 16px to 14px to accommodate smaller screen sizes.
2. Everything scales accordingly.
Screenshots on 125% zoom:
Before:
After:
> Update base font-size from 16px to 14px

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
[CT-2374](https://datacamp.atlassian.net/browse/CT-2374)
This is a growth experiment to bring visitors to workspace.
- Add a button "Run in workspace" in each example code cell. For now this will just send people to the workspace landing page as we don't have a way to create a workspace from a block of code. If we notice good traction, this will be a follow up to implement this feature.
- Add a link to workspace below each example code cell
On desktop:
On phone:
> Add "Run in workspace" button in Example code cells

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
Fixes [CT-2476](https://datacamp.atlassian.net/browse/CT-2476)
We now send the rdocs path in the params which will be used to access the api endpoint to retrieve the example code for pre populating a workspace. Now also send the title of the page.
> feat: added rdcos path and title in the params for opening in workspace

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
Removed button to run in workspace and now link below example directs to landing page of workspace.
> feat: removed workspace button and changed url to direct to landing page

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
Remove the `Run in Workspace` button when accessing RDocs on a mobile/ipad device. 
Text on button needs to be confirmed
Note : userAgent is flakey and [recommendation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) is to use maxTouchpoints.
> feat: remove the workspace button when accessing on mobile/ipad

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
Detect if device is mobile and if it is, remove the run in workspace button. This is a temporary fix as we will have the button visible for mobile once DC r studio is live.
> feat: mobile device detection for button

- pages/link/[topic].tsx
The links in the “See Also” section on topic pages lead to a 404. This is very annoying since RDocumentation is often the first result for searches related to R packages. The missing page is:
`/link/:topic?package=:package&version=:version`
And it should point to:
`/packages/:package/versions/:version/topics/:topic`
However, It can’t be simply fixed by redirecting to the correct URL because the function names in the “See Also” section don’t always map directly to topic pages. There is an [API endpoint](https://github.com/datacamp/RDocumentation-app/blob/aa71a42af087a850df69d5c7ecbc01316cc31f0e/api/controllers/TopicController.js#L263-L367) with the same path that resolves the correct topic page and fallbacks with a search results:
`[API_URL]/link/:topic?package=:package&version=:version` …
> fix: fix broken links in the “See Also” section

- pages/link/[topic].tsx
Some of the links are formatted as `function_name()` or `library::function_name()` instead of just `function_name`. This is the convention in the tidyverse's docs.
This change simply removes the brackets and splits the library and function names.
Link to `tidyselect::vars_pull()` from tidyr:
Before: `/link/tidyselect::vars_pull()?package=tidyr`
After: `/link/vars_pull?package=tidyselect`
More info in #81.
> fix: broken crosslinks (#81, #74)

- pages/packages/[package]/versions/[version]/topics/[topic].tsx
When the example is only 1 line, resize the button to fit the cell.
**Before:**
**After:**
> [CT-3408] Fix workspace button styling

- components/Html.tsx
- pages/packages/[package]/versions/[version]/topics/[topic].tsx
- styles/index.css
Fixes [CT-3571](https://datacamp.atlassian.net/browse/CT-3571)
Arguments are now part of `sections` instead of `args`. This update should work both for new packages that use `sections` and old packages that use `args`.
> [CT-3571] Fix rendering of arguments for upcoming API change

- components/Html.tsx
- pages/_document.tsx
- pages/packages/[package]/versions/[version]/topics/[topic].tsx
[TICKET](https://datacamp.atlassian.net/browse/CT-3677?atlOrigin=eyJpIjoiYzE4OGI2OTM4M2JhNDhkMTk5NTU2N2U4Y2VlM2QyNjgiLCJwIjoiaiJ9)
Add <meta> link to verify for google-search-console
> chore: add gsc meta tag for verification

- components/PackageReadMePlaceholder.tsx
- pages/packages/[package]/versions/[version].tsx
[TICKET](https://datacamp.atlassian.net/browse/CT-3782?atlOrigin=eyJpIjoiZWZhMDZkNGQ2YTE0NGU3NzllNjA2OGNiZTQ1MzMxNzAiLCJwIjoiaiJ9)
[ISSUE](https://github.com/datacamp/rdocumentation-2.0/issues/107#issue-1249366451)
Removed "readme not available" message and replaced with package metadata.
Before:
After:
Before:
After:
Replace the readme not available message to improve user experience.
> [CT-3782] chore: replace readme not available message

- pages/packages/[package]/versions/[version].tsx
Small ui fix to remove the functions section if there aren't any functions in the package. I think it looks cleaner. (readme will be fixed once merged)
Before:
After:
> fix: hide functions list if package has no functions

- pages/search.tsx
[TICKET](https://datacamp.atlassian.net/browse/CT-3781?atlOrigin=eyJpIjoiNjIxMTU1Y2VhYWY0NGYxOWE2MmVkMjg5ZmI1NTMxMjIiLCJwIjoiaiJ9)
ISSUES: #110 #68 
Changes made: 
- Fix the /search_functions api call. Without the packages parameter, the controller would throw an error for certain query parameters (see issues).
- Fix the constant loading state when results are not available, I think its better to just say no results.
The below examples are related to the issues.
Before:
After:
> [CT-3781] fix: empty search results and constant loading

- package.json
- pages/packages/[package]/versions/[version]/topics/[topic].tsx
- yarn.lock
Highlighting syntax of runnable code to encourage user to run the code. (Run this code)
Let me know if changes to highlighting theme are required.
[TICKET](https://datacamp.atlassian.net/browse/CT-3798?atlOrigin=eyJpIjoiOWM0YTQ1YjVmNjI3NGMzYmE0NTA0OWZhZDM2OGU1NGEiLCJwIjoiaiJ9)
[ISSUE](https://github.com/datacamp/rdocumentation-2.0/issues/14) #14 
Light mode before:
Light mode after: 
Dark mode before:
Dark mode after:
> feat: syntax highlighting for run this code

- components/Footer.tsx
When promo banner is showing up, the "Powered by DataCamp" is below the fold. This fixes it.
> chore: add position absolute to footer

- lib/gtag.ts
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/packages/[package]/versions/[version]/topics/[topic].tsx
- yarn.lock
This PR should migrate from Google Analytics UA to GA4, [epic link](https://datacamp.atlassian.net/browse/FP-740) is here with all the work being done for this migration:
- Replace react-ga with react-ga4
- Use the new `G-{id}` web data stream id
- Remove the manual SPA page view events that were hooked into the route
- Remove a duped injection of the gtag script in `_document.tsx` (react-ga4 injects this already)
- Update the "Run in workspace" event call to use the GA4 format/function
Based off the research I've done, this should work out of the box with Next and GA4 thanks to GA4's "enhanced measurement" in data streams. All we need to do is is enable "Page changes based on history browser events" in the web data stream settings. I won't do that until we're QA'ing on Staging though as …
> [FP-769] Migrate to GA4

- pages/search.tsx
Ticket: https://datacamp.atlassian.net/browse/COMM-5586
Note: This is only part of the solution. For some functions, the API call errors with a 500. We will need to fix that as well.
Before:
After:
> [COMM-5586] Remove package param from functions search query to fix error with functions not loading

- components/CourseAds.tsx
- components/HomePageLinks.tsx
- components/HomeSearchBar.tsx
- components/Layout.tsx
- components/Navbar.tsx
- components/PackageFunctionList.tsx
- helpers/hooks/useRenderCourseAds.ts
- pages/index.tsx
- pages/packages/[package]/versions/[version]/topics/[topic].tsx
1. Add a course adds component that is based on a hardcoded list of URLs that are often visited.
2. Apply style design changes to the homepage
- Fix the logo and the button sizes on the page
- Enforce lightmode for the search bar
- Increase fontsizes
- Link to datacamp when clicking on powered by datacamp and link to / when clicking on rdocumentation
- minor copy changes
> [OGE-1878] add course ads and apply styling feedback

- pages/packages/[package]/versions/[version].tsx
- Avoid rendering 1st January 1970 date for last published at (fixes this for all cases)
- When this date is undefined / nullish use the last updated at date for correctness
https://datacamp.atlassian.net/browse/OGE-1827
> [OGE-1827] feat: last published date

- components/PackageSidebar.tsx
- helpers/hooks/useHasCollaborator.ts
This pull request proposes an update to the `PackageSidebar` component to enhance the handling of the maintainer's information. The changes introduce a new state to track the availability of the maintainer and update the UI accordingly.
Following the end of Depsy back in 2018, there is no new data incoming - meaning any authors published after March 2018 will throw a 404 on the collaborator/maintainer page on rdocs.
> chore: remove the link if the author is not available
